################################################################################
# HOMELAB
################################################################################

include:
    #############################################################################
    # TRAEFIK (CORE)
    #############################################################################

    # - apps/traefik/docker-compose.yaml # Traefik (Reverse Proxy)
    # - apps/duckdns.yaml # DuckDNS (Dynamic DNS)
    # - apps/oauth.yaml # OAuth (Authentication)
    
    - apps/socket-proxy.yaml # Docker Socket Proxy (Security)
    - apps/caddy.yaml # Caddy (Reverse Proxy)
    - apps/whoami.yaml # WhoAmI (Test WebServer)
    - apps/cloudflared.yaml
    # - apps/traefik.yaml
    # - apps/whoami.yaml
    # - apps/authelia.yaml # Authelia (Authentication)
    # - apps/lldap.yaml # LLDap (Identity Management)
    # - apps/gluetun.yaml

    #############################################################################
    # MEDIA
    #############################################################################

    # - apps/heimdall.yaml # Heimdall (Landing Page)
    # - apps/plex.yaml # Plex (Media Server)

    # - apps/jellyfin.yaml # Jellyfin (Media Server)
    # - apps/qbittorrent.yaml # qBittorrent (Torrent Client)

    # - apps/jackett.yaml
    # - apps/prowlarr.yaml # Prowlarr (Indexer)
    # - apps/flaresolverr.yaml # FlareSolverr (Cloudflare and DDoS-GUARD Bypasser)
    # - apps/sonarr.yaml # Sonarr (TV Show Downloads)
    # - apps/radarr.yaml # Radarr (Movie Downloads)
    # - apps/jellyseerr.yaml # Jellyseerr (Media Requests)
    # - apps/bazarr.yaml # Subtitle (Subtitle Downloads)

    # - apps/sabnzbd.yaml # SABnzbd (Usenet Downloading)
    # - apps/nzbhydra.yaml # NZBHydra2 (Usenet Browsing)
    # - apps/readarr.yaml # Readarr (Ebook Downloads)
    # - apps/calibre.yaml # Calibre (Books Management)
    # - apps/calibre-web.yaml # Calibre Web-UI

    #############################################################################
    # UTILITIES
    #############################################################################

    # - apps/watchtower.yaml #  Watchtower (Container Updating)
    # - apps/postgres.yaml # PostgreSQL (Shared Database)
    # - apps/sftpgo.yaml # SFTPGo (File Management)
    # - apps/pihole.yaml # Pi-hole (DNS Ad-Blocking)
    # - apps/portainer.yaml # Portainer (Container Management)

    #############################################################################
    # MISCELLANEOUS
    #
    # * Note the existing services that are disabled by default.
    #############################################################################

    # - apps/chat-gpt-next-web.yaml # ChatGPT Next Web
    # - apps/chatgpt-in-slack.yaml # ChatGPT Slack Bot
    # - apps/libreoffice.yaml # LibreOffice (Office Suite)
    # - apps/umami.yaml # Umami Analytics
    # - apps/homeassistant/docker-compose.yaml # Home Assistant (Smart Home)
    # - apps/healthchecks.yaml # Healthchecks (Monitoring)

################################################################################
# NETWORK CONFIGURATION
################################################################################

networks:
    caddy:
        driver: bridge
    traefik:
        driver: bridge
    docker:
        driver: bridge
#     internal:
#         driver: bridge
#         ipam:
#             config:
#                 - subnet: 192.168.92.0/24
